/*
 * HR management Api
 *
 * Ambulance HR management API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ambulance_hr

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

type UserManagementAPI interface {

	// internal registration of api routes
	addRoutes(routerGroup *gin.RouterGroup)

	// AddPersonalDocument - Add personal document to user
	AddPersonalDocument(ctx *gin.Context)

	// LoginUser - Login user
	LoginUser(ctx *gin.Context)

	// UpdatePersonalDocument - Update personal document of user
	UpdatePersonalDocument(ctx *gin.Context)
}

// partial implementation of UserManagementAPI - all functions must be implemented in add on files
type implUserManagementAPI struct {
}

func newUserManagementAPI() UserManagementAPI {
	return &implUserManagementAPI{}
}

func (this *implUserManagementAPI) addRoutes(routerGroup *gin.RouterGroup) {
	routerGroup.Handle(http.MethodPost, "/user/:userId/personalDocument", this.AddPersonalDocument)
	routerGroup.Handle(http.MethodPost, "/login", this.LoginUser)
	routerGroup.Handle(http.MethodPut, "/user/:userId/personalDocument", this.UpdatePersonalDocument)
}
