/*
 * HR management Api
 *
 * Ambulance HR management API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ambulance_hr

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

type HRManagementAPI interface {

	// internal registration of api routes
	addRoutes(routerGroup *gin.RouterGroup)

	// CreateUser - Create new user
	CreateUser(ctx *gin.Context)

	// DeleteUser - Delete user by id
	DeleteUser(ctx *gin.Context)

	// GetUser - Get user by id
	GetUser(ctx *gin.Context)

	// GetUsers - Get all users
	GetUsers(ctx *gin.Context)

	// UpdateUserDepartment - Update user department
	UpdateUserDepartment(ctx *gin.Context)
}

// partial implementation of HRManagementAPI - all functions must be implemented in add on files
type implHRManagementAPI struct {
}

func newHRManagementAPI() HRManagementAPI {
	return &implHRManagementAPI{}
}

func (this *implHRManagementAPI) addRoutes(routerGroup *gin.RouterGroup) {
	routerGroup.Handle(http.MethodPost, "/users", this.CreateUser)
	routerGroup.Handle(http.MethodDelete, "/user/:userId", this.DeleteUser)
	routerGroup.Handle(http.MethodGet, "/user/:userId", this.GetUser)
	routerGroup.Handle(http.MethodGet, "/users", this.GetUsers)
	routerGroup.Handle(http.MethodPatch, "/user/:userId/department", this.UpdateUserDepartment)
}
