/*
 * HR management Api
 *
 * Ambulance HR management API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ambulance_hr

type UserDto struct {

	// Unique identifier of the user
	Id string `json:"id"`

	// Name of the user
	Name string `json:"name"`

	Role RoleEnum `json:"role"`

	// Phone number of the user
	Phone string `json:"phone"`

	Email string `json:"email"`

	Department DepartmentEnum `json:"department"`

	PersonalDocument []PersonalDocument `json:"personalDocument"`
}
