/*
 * HR management Api
 *
 * Ambulance HR management API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ambulance_hr

type UserList struct {

	// Unique identifier of the user
	Id string `json:"id"`

	// Name of the user
	Name string `json:"name"`

	Role RoleEnum `json:"role"`

	Department DepartmentEnum `json:"department"`
}
