/*
 * HR management Api
 *
 * Ambulance HR management API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ambulance_hr

type DepartmentEnum string

// List of DepartmentEnum
const (
	GP               DepartmentEnum = "GP"
	SURGERY          DepartmentEnum = "Surgery"
	PEDIATRICS       DepartmentEnum = "Pediatrics"
	GYNECOLOGY       DepartmentEnum = "Gynecology"
	NEUROLOGY        DepartmentEnum = "Neurology"
	DEPARTMENT_OTHER DepartmentEnum = "Other"
)
