/*
 * HR management Api
 *
 * Ambulance HR management API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ambulance_hr

type RoleEnum string

// List of RoleEnum
const (
	DOCTOR        RoleEnum = "Doctor"
	NURSE         RoleEnum = "Nurse"
	ADMINISTRATOR RoleEnum = "Administrator"
	RECEPTIONIST  RoleEnum = "Receptionist"
	TECHNICIAN    RoleEnum = "Technician"
	ROLE_OTHER    RoleEnum = "Other"
)
