/*
 * HR management Api
 *
 * Ambulance HR management API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ambulance_hr

import (
	"github.com/gin-gonic/gin"
)

func AddRoutes(engine *gin.Engine) {
	group := engine.Group("/api")

	{
		api := newHRManagementAPI()
		api.addRoutes(group)
	}

	{
		api := newUserManagementAPI()
		api.addRoutes(group)
	}

}
